<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Translatable\HasTranslations;

class Setting extends Model
{
    use HasFactory, HasTranslations;

    protected $fillable = [
        'logo_img',
        'tiktok_link',
        'insta_link',
        'live_link',
        'sale_link',
        'info_title',
        'info_subtitle',
        'info_desc',
        'banner_img',
        'banner_title',
        'banner_link',
        'services_home_title',
        'services_subtitle',
        'gallery_home_title',
        'gallery_subtitle',
        'news_home_title',
        'news_subtitle',
        'footer_title',
        'address',
        'phone',
        'email',
        'work_time',
        'copy_write',
        'about_bg_img',
        'about_title',
        'about_old_desc',
        'about_new_desc',
        'about_old_img',
        'about_new_img',
        'services_bg_img',
        'services_title',
        'services_desc',
        'news_title',
        'news_bg_img',
        'suggestion_title',
        'suggestion_bg_img',
        'rules_title',
        'rules_bg_img',
        'rules_desc', 
        'education_bg_img',
        'education_title',
        'education_desc',
        'breeding_title',
        'breeding_desc',
        'breeding_bg_img',
        'faq_title',
        'faq_bg_img',
        'galery_title',
        'contact_title',
        'contact_bg_img',
        'longitude',
        'latitude',
        'marker_path',

       
    ];

    protected $translatable = ['info_subtitle',
    'info_desc',
    'banner_title',
    'services_home_title',
    'services_subtitle',
    'gallery_home_title',
    'gallery_subtitle',
    'news_home_title',
    'news_subtitle',
    'footer_title',
    'address',
    'copy_write',
    'about_title',
    'about_old_desc',
    'about_new_desc',
    'services_title',
    'services_desc',
    'news_title',
    'suggestion_title',
    'rules_title',
    'rules_desc', 
    'education_title',
    'education_desc',
    'breeding_title',
    'breeding_desc',
    'faq_title',
    'galery_title',
    'contact_title',
 ];
}
